environments:
  default:
    name: akspriv-yoursquadnamehere-hlg
    resource_group: rg-yoursquadnamehere-app-hlg
    service_principal_credential_id: aks-sp
    subscription_id: subscription_id_provided_to_your_squad
  prd:
    name: akspriv-yoursquadnamehere-prd
    resource_group: rg-yoursquadnamehere-app-prd
    service_principal_credential_id: aks-sp
    subscription_id: subscription_id_provided_to_your_squad