spring:
  jpa:
    open-in-view: false
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  port: 8080

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include=*: