name: Deploy to staging

env:
  CONTEXT_DIR: './'
  IMAGE_NAME: portifolify
  DOCKERFILE: ./Dockerfile
  CAPROVER_APP: portifolify-stg
  SPRING_PROFILES_ACTIVE: hlg

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Log in to registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Code Quality Checks
        run: mvn --batch-mode --update-snapshots verify pmd:pmd pmd:cpd

      - name: Run Tests
        run: mvn --batch-mode --update-snapshots test

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.CONTEXT_DIR }}
          file: ${{ env.DOCKERFILE }}
          build-args: |
            SPRING_PROFILES_ACTIVE=${{ env.SPRING_PROFILES_ACTIVE }}
          push: false
          tags: ${{ env.IMAGE_NAME }}

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
          echo "FULL_IMAGE_NAME=$IMAGE_ID:$VERSION" >> $GITHUB_ENV

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@d76580d79952f6841c453bb3ed37ef452b19752c
        with:
          server: ${{ secrets.CAPROVER_HOST }}
          app: ${{ env.CAPROVER_APP }}
          token: '${{ secrets.CAPROVER_APP_TOKEN_HLG }}'
          image: '${{ env.FULL_IMAGE_NAME }}'

